version: 2
updates:
  - package-ecosystem: "github-actions"
    directories: 
    - "../../maven"
    - "../../dependency-management"
    - "../../misc"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "build"
