# References:
# https://opensource.google/documentation/reference/thirdparty/licenses
# https://spdx.org/licenses/
allow_licenses:
  # Unencumbered: Licenses that declare the code is "free for any use".
  - '0BSD'
  - 'CC0-1.0'
  - 'Unlicense'

  # Notice: Licenses with minimal restrictions, allowing original or modified third-party software to be shipped, but requiring inclusion of an original copyright notice or advertising clause in external distributions.
  - 'AFL-1.1'
  - 'AFL-1.2'
  - 'AFL-2.0'
  - 'AFL-2.1'
  - 'AFL-3.0'
  - 'AMPAS'
  - 'Apache-1.0'
  - 'Apache-1.1'
  - 'Apache-2.0'
  - 'Artistic-1.0'
  - 'Artistic-1.0-cl8'
  - 'Artistic-1.0-Perl'
  - 'Artistic-2.0'
  - 'Beerware'
  - 'BSD-2-Clause'
  - 'BSD-2-Clause-FreeBSD'
  - 'BSD-2-Clause-NetBSD'
  - 'BSD-2-Clause-Patent'
  - 'BSD-3-Clause'
  - 'BSD-3-Clause-Attribution'
  - 'BSD-3-Clause-Clear'
  - 'BSD-3-Clause-LBNL'
  - 'BSD-4-Clause'
  - 'BSD-4-Clause-UC'
  - 'BSD-Protection'
  - 'BSL-1.0'
  - 'CC-BY-1.0'
  - 'CC-BY-2.0'
  - 'CC-BY-2.5'
  - 'CC-BY-3.0'
  - 'CC-BY-4.0'
  - 'CDLA-Permissive-1.0'
  - 'CDLA-Permissive-2.0'
  - 'CERN-OHL-P-2.0'
  - 'FTL'
  - 'ISC'
  - 'ImageMagick'
  - 'JSON'
  - 'LPL-1.0'
  - 'LPL-1.02'
  - 'Libpng'
  - 'libtiff'
  - 'Linux-OpenIB'
  - 'MIT'
  - 'MIT-CMU'
  - 'MS-PL'
  - 'NCSA'
  - 'NIST-Software'
  - 'OpenSSL'
  - 'PHP-3.0'
  - 'PHP-3.01'
  - 'PostgreSQL'
  - 'PSF-2.0'
  - 'Python-2.0'
  - 'SGI-B-1.0'
  - 'SGI-B-1.1'
  - 'SGI-B-2.0'
  - 'SHL-0.5'
  - 'SHL-0.51'
  - 'TCP-wrappers'
  - 'UPL-1.0'
  - 'Unicode-DFS-2015'
  - 'Unicode-DFS-2016'
  - 'Unicode-TOU'
  - 'W3C'
  - 'W3C-19980720'
  - 'W3C-20150513'
  - 'WTFPL'
  - 'X11'
  - 'Xnet'
  - 'ZPL-1.1'
  - 'ZPL-2.0'
  - 'ZPL-2.1'
  - 'Zend-2.0'
  - 'Zlib'
  - 'zlib-acknowledgement'
