= Summary
:lang: en

[[header]]
[[toc]]
[[toctitle]]
Table of Contents

* link:#_summary[1. Summary]
* link:#_packages[2. Packages]
** link:#_pkgmavenorg_apache_tomcat_embedtomcat_embed_core10_1_20[2.1.
pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@10.1.20]
** link:#_pkgmavenorg_xmlunitxmlunit_core2_9_1[2.2.
pkg:maven/org.xmlunit/xmlunit-core@2.9.1]

[[content]]
[[_summary]]
== 1. Summary

* Unknown: 0
* Low: 1
* Medium: 0
* High: 1
* Critical: 0
* Total: 2

[[_packages]]
== 2. Packages

[[_pkgmavenorg_apache_tomcat_embedtomcat_embed_core10_1_20]]
=== 2.1. pkg:maven/org.apache.tomcat.embed/tomcat-embed-core@10.1.20

*Advisor: OSV*

* GHSA-wm9w-rjj3-j356
+
** Source: https://nvd.nist.gov/vuln/detail/CVE-2024-34750 +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source:
https://github.com/apache/tomcat/commit/2344a4c0d03e307ba6b8ab6dc8b894cc8bac63f2 +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source:
https://github.com/apache/tomcat/commit/2afae300c9ac9c0e516e2e9de580847d925365c3 +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source:
https://github.com/apache/tomcat/commit/9fec9a82887853402833a80b584e3762c7423f5f +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source: https://github.com/apache/tomcat +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source:
https://lists.apache.org/thread/4kqf0bc9gxymjc2x7v3p7dvplnl77y8l +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source: https://tomcat.apache.org/security-10.html +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source: https://tomcat.apache.org/security-11.html +
Severity: [.severity-high]#7.5# (CVSS:3.1)
** Source: https://tomcat.apache.org/security-9.html +
Severity: [.severity-high]#7.5# (CVSS:3.1)

[[_pkgmavenorg_xmlunitxmlunit_core2_9_1]]
=== 2.2. pkg:maven/org.xmlunit/xmlunit-core@2.9.1

*Advisor: OSV*

* GHSA-chfm-68vv-pvw5

[[footer]]
[[footer-text]]
Last updated 2024-07-17 10:25:49 UTC
