name: OSS Review Toolkit
on:
  workflow_call:

jobs:
  ort:
    runs-on: ubuntu-latest
    steps:
      - name: Use HTTPS instead of SSH for Git cloning
        run: git config --global url.https://github.com/.insteadOf ssh://git@github.com/
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Download report template
        run: |
          curl -o cve_summary_report_template.ftl https://raw.githubusercontent.com/IsyFact/isy-github-actions-templates/v1.2.0/ort-config/cve_summary_report_template.ftl
      - name: Download license management config files
        run: |
          echo "downloading ORT License Management config files..."
          curl -o license-classifications.yml https://raw.githubusercontent.com/IsyFact/isy-github-actions-templates/feature/main_OSS_Review_Toolkit/ort-config/license-classifications.yml
          curl -o evaluator.rules.kts https://raw.githubusercontent.com/IsyFact/isy-github-actions-templates/feature/main_OSS_Review_Toolkit/ort-config/evaluator.rules.kts
          echo "ORT License Management config files download successful"
      - name: Run GitHub Action for ORT
        uses: oss-review-toolkit/ort-ci-github-action@v1
        with:
          docker-cli-args:
            --mount type=bind,source=${{ github.workspace }},target=/home/ort/.ort/templates/
            --mount type=bind,source=${{ github.workspace }},target=/home/ort/.ort/config/
          report-formats: WebApp,StaticHtml,HtmlTemplate -O HtmlTemplate=template.path=/home/ort/.ort/templates/cve_summary_report_template.ftl
      - name: Download workflow artifacts
        uses: actions/download-artifact@v4
        with:
          path: ${{ github.workspace }}/ort-reports
      - name: Log artifacts
        run: |
          echo $(pwd)
          echo $GIT_REPO_PATH:/repo
          echo $GIT_REPO_PATH:/repo
          docker run -v $(pwd)
          ls -R ${{ github.workspace }}/ort-reports
