name: PR-Agent Template

on:
  workflow_call:
    secrets:
      OPENAI_KEY:
        description: 'API key for ChatGPT'
        required: true

jobs:
  PrAgent:
    if: ${{ github.event.sender.type != 'Bot' }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
      - name: Run PR-Agent
        uses: Codium-ai/pr-agent@v0.26
        env:
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
