name: Update Antora Version Template
on:
  workflow_call:

jobs:
  UpdateAntoraVersion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up path for antora.yml
        run: |
          repo_name="${{ github.repository }}"
          repo_name="${repo_name#*/}"  
          echo "ANTORA_PATH=${repo_name}-doc/antora.yml" >> $GITHUB_ENV

      - name: Extract version details
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Update antora.yml with the new version
        run: |
          version=${{ env.RELEASE_VERSION }}
          sed -i "s|^version: *'.*'|version: '$version'|" ${{ env.ANTORA_PATH }}
          sed -i "s|^display_version: *'.*'|display_version: '$version'|" ${{ env.ANTORA_PATH }}

      - name: Commit and push antora.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -u
          git commit -m "docs: updated antora.yml to version ${{ env.RELEASE_VERSION }}"
          git push origin HEAD:${{ github.ref }}
